#!/bin/bash

IDENTIFIER="au.com.errorfreeit.setsystemclockatloginwindow"
LAUNCH_AGENT_PLIST="/Library/LaunchAgents/$IDENTIFIER.plist"

# Load the LaunchAgent.
/bin/launchctl load "$LAUNCH_AGENT_PLIST"

# To avoid OS X 10.9 ending the installer with an error code: 1 "nothing found to load"
exit 0